from __future__ import annotations

import json
import logging
import re
from collections.abc import AsyncGenerator
from uuid import UUID

import httpx
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.responses import StreamingResponse

from api.config import settings
from api.db.models import (
    Conversation,
    Design,
    GeneratedCode,
    GeneratedTask,
    PullRequest,
    Specification,
    User,
)
from api.dependencies import get_current_user, get_db
from api.services.code_parser import parse_code_blocks
from api.services.github import GitHubClient, GitHubError
from shared_schemas import PRCreateRequest, PRStatus, PullRequestRead, PullRequestUpdate

logger = logging.getLogger(__name__)

router = APIRouter(tags=["pull-requests"])


def _sse_event(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


async def _get_user_conversation(
    conversation_id: UUID,
    user: User,
    db: AsyncSession,
) -> Conversation:
    result = await db.execute(
        select(Conversation).where(
            Conversation.id == conversation_id,
            Conversation.user_id == user.id,
        )
    )
    conversation = result.scalar_one_or_none()
    if conversation is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found",
        )
    return conversation


async def _get_user_pr(
    pr_id: UUID,
    user: User,
    db: AsyncSession,
) -> PullRequest:
    result = await db.execute(
        select(PullRequest)
        .join(Conversation, PullRequest.conversation_id == Conversation.id)
        .where(
            PullRequest.id == pr_id,
            Conversation.user_id == user.id,
        )
    )
    pr = result.scalar_one_or_none()
    if pr is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Pull request not found",
        )
    return pr


def _sanitize_branch_name(text: str) -> str:
    """Create a valid git branch name from text."""
    sanitized = re.sub(r"[^a-zA-Z0-9_/-]", "-", text.lower())
    sanitized = re.sub(r"-+", "-", sanitized).strip("-")
    return sanitized[:80]


def _build_pr_description(
    spec_title: str,
    design_title: str,
    task_title: str,
    code_id: str,
    files: list[str],
) -> str:
    """Build a PR description with traceability links."""
    file_list = "\n".join(f"- `{f}`" for f in files)
    return (
        f"## Traceability\n\n"
        f"- **Specification**: {spec_title}\n"
        f"- **Design**: {design_title}\n"
        f"- **Task**: {task_title}\n"
        f"- **Code ID**: `{code_id}`\n\n"
        f"## Files Changed\n\n{file_list}\n\n"
        f"---\n"
        f"*Auto-generated by Thirdy Pipeline*"
    )


# --- Create PR endpoint (SSE streaming) ---


@router.post("/conversations/{conversation_id}/pull-requests/create")
async def create_pull_request(
    conversation_id: UUID,
    request: Request,
    body: PRCreateRequest,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    conversation = await _get_user_conversation(conversation_id, user, db)

    # Validate GitHub config
    if not settings.github_token or not settings.github_owner or not settings.github_repo:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="GitHub configuration is missing. Set GITHUB_TOKEN, GITHUB_OWNER, and GITHUB_REPO.",
        )

    # Load approved code
    code_result = await db.execute(
        select(GeneratedCode)
        .join(Conversation, GeneratedCode.conversation_id == Conversation.id)
        .where(
            GeneratedCode.id == body.code_id,
            GeneratedCode.conversation_id == conversation_id,
            GeneratedCode.status == "approved",
            Conversation.user_id == user.id,
        )
    )
    code = code_result.scalar_one_or_none()
    if code is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Approved code not found",
        )

    # Load task (parent of code)
    task_result = await db.execute(
        select(GeneratedTask).where(GeneratedTask.id == code.task_id)
    )
    task = task_result.scalar_one_or_none()
    if task is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Task not found",
        )

    # Load design (parent of task)
    design_result = await db.execute(
        select(Design).where(Design.id == task.design_id)
    )
    design = design_result.scalar_one_or_none()
    if design is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Design not found",
        )

    # Load spec (parent of design)
    spec_result = await db.execute(
        select(Specification).where(Specification.id == design.specification_id)
    )
    spec = spec_result.scalar_one_or_none()
    if spec is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Specification not found",
        )

    # Cache values for generator
    conv_id = conversation.id
    code_id = code.id
    code_content = code.content
    task_title = task.title
    design_title = design.title
    spec_title = spec.title
    get_session = request.app.state.session_factory

    async def event_generator() -> AsyncGenerator[str]:
        yield _sse_event("pr_started", {
            "conversation_id": str(conv_id),
            "code_id": str(code_id),
        })

        try:
            # Parse code blocks from markdown
            code_files = parse_code_blocks(code_content)
            if not code_files:
                raise ValueError("No code files found in the generated code content")

            # Create branch name
            branch_name = f"thirdy/{_sanitize_branch_name(task_title)}-{str(code_id)[:8]}"
            pr_title = f"feat: {task_title}"
            file_paths = [f.path for f in code_files]
            pr_body = _build_pr_description(
                spec_title, design_title, task_title, str(code_id), file_paths
            )

            # GitHub operations
            async with httpx.AsyncClient(timeout=30.0) as http:
                gh = GitHubClient(
                    token=settings.github_token,
                    owner=settings.github_owner,
                    repo=settings.github_repo,
                    http=http,
                )

                # Get base branch SHA
                base_sha = await gh.get_default_branch_sha(settings.github_base_branch)

                # Create branch
                await gh.create_branch(branch_name, base_sha)
                yield _sse_event("branch_created", {"branch_name": branch_name})

                # Commit files
                for cf in code_files:
                    await gh.create_or_update_file(
                        branch=branch_name,
                        path=cf.path,
                        content=cf.content,
                        message=f"feat: add {cf.path}",
                    )
                yield _sse_event("files_committed", {
                    "file_count": len(code_files),
                    "files": file_paths,
                })

                # Create PR
                pr_response = await gh.create_pull_request(
                    title=pr_title,
                    body=pr_body,
                    head=branch_name,
                    base=settings.github_base_branch,
                )

            pr_number = pr_response["number"]
            pr_url = pr_response["html_url"]

            yield _sse_event("pr_created", {
                "pr_number": pr_number,
                "pr_url": pr_url,
            })

            # Save to DB
            async with get_session() as stream_db:
                pr = PullRequest(
                    conversation_id=conv_id,
                    code_id=code_id,
                    pr_number=pr_number,
                    pr_url=pr_url,
                    branch_name=branch_name,
                    title=pr_title,
                    description=pr_body,
                    status="created",
                )
                stream_db.add(pr)
                await stream_db.commit()
                await stream_db.refresh(pr)

                pr_read = PullRequestRead.model_validate(pr)
                yield _sse_event("done", pr_read.model_dump(mode="json"))

        except GitHubError as e:
            logger.exception("GitHub API error during PR creation")
            # Save failed PR record
            async with get_session() as stream_db:
                pr = PullRequest(
                    conversation_id=conv_id,
                    code_id=code_id,
                    pr_number=None,
                    pr_url=None,
                    branch_name=branch_name if "branch_name" in dir() else "unknown",
                    title=pr_title if "pr_title" in dir() else task_title,
                    description=str(e),
                    status="failed",
                    error_message=str(e),
                )
                stream_db.add(pr)
                await stream_db.commit()
            yield _sse_event("error", {"detail": str(e)})

        except Exception as e:
            logger.exception("Error during PR creation")
            yield _sse_event("error", {"detail": str(e)})

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


# --- CRUD endpoints ---


@router.get(
    "/conversations/{conversation_id}/pull-requests",
    response_model=list[PullRequestRead],
)
async def list_pull_requests(
    conversation_id: UUID,
    offset: int = Query(0, ge=0),
    limit: int = Query(50, ge=1, le=100),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _get_user_conversation(conversation_id, user, db)
    result = await db.execute(
        select(PullRequest)
        .where(PullRequest.conversation_id == conversation_id)
        .order_by(PullRequest.created_at.asc())
        .offset(offset)
        .limit(limit)
    )
    return result.scalars().all()


@router.get("/pull-requests/{pr_id}", response_model=PullRequestRead)
async def get_pull_request(
    pr_id: UUID,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    return await _get_user_pr(pr_id, user, db)


@router.patch("/pull-requests/{pr_id}", response_model=PullRequestRead)
async def update_pull_request(
    pr_id: UUID,
    body: PullRequestUpdate,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    pr = await _get_user_pr(pr_id, user, db)
    if body.status is not None:
        pr.status = body.status.value
    await db.commit()
    await db.refresh(pr)
    return pr


@router.delete(
    "/pull-requests/{pr_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
async def delete_pull_request(
    pr_id: UUID,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    pr = await _get_user_pr(pr_id, user, db)
    await db.delete(pr)
    await db.commit()
